"""
Header like file with all static defines.
"""

START_DATA = "<~+~>"
STOP_DATA = "~<+>~"

WAIT_AFTER_OPENING_PORT = 1

SERIAL_SPEED = 9600
RECEIVED_BUFFER_SIZE = 20
PRINTF_BUFFER_SIZE = 15
COMAND_ENDING_CONST = '\n'
READY_TO_READ = "Ready to read\n"
HANSHAKE_CONFIRM_REQUEST_CODE = "42a"
HANSHAKE_CONFIRMATION_CODE = "42b"
AKW_TIME_MS_CODE = "atm"
CODE_STOPED_RESPONSE = "fin"
SERIAL_BUFFER_SIZE = 64

START_CODE = "srt"
STOP_CODE = "stp"

SLEEP_TIME = 0.01
WAIT_FOR = 100

REPEAT_FOR = 3

DEAMON_LOOP_COUNT = 50
COMUNICATION_TIME_MS = 100